service: serverless-crud

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: dev
  iam:
    role:
        statements:
            - Effect: Allow
              Action:
                - dynamodb:DescribeTable
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:DeleteItem
              Resource: "arn:aws:dynamodb:us-east-1:*:*"

functions:
  Bikes:
    handler: handler.bikes
    events:
      - http:
          path: bikes/{id}
          method: get
          cors: true
      - http:
          path: bikes/{id}
          method: patch
          cors: true
  Pings:
    handler: handler.pings
    events:
      - http:
          path: pings/{id}
          method: post
          cors: true
      - http:
          path: pings/{id}
          method: get
          cors: true
  Users:
    handler: handler.users
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
      - http:
          path: users/{id}
          method: patch
          cors: true



resources:
  Resources:
    PingsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: BikeID
            AttributeType: S
          -
            AttributeName: time
            AttributeType: N
        KeySchema:
          -
            AttributeName: BikeID
            KeyType: HASH
          -
            AttributeName: time
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'FindYourBikePings'
    BikesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: BikeID
            AttributeType: S
        KeySchema:
          -
            AttributeName: BikeID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'FindYourBikeBikes'
    UsersDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: UserID
            AttributeType: S
        KeySchema:
          -
            AttributeName: UserID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'FindYourBikeUsers'
    ReportsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      #DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: ReportID
            AttributeType: S
        KeySchema:
          -
            AttributeName: ReportID
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'FindYourBikeReports'
